version: "3"
services:
  consumer:
    image: client
    ports:
      - "8090:8090"
    networks:
      - consumer-producer
    depends_on:
      - producer
 
  producer:
    image: service
    ports:
      - "8080:8080"
    networks:
      - consumer-producer 

networks:
  consumer-producer: